#computer guess the number it generates

# computer generates a random number between 1 and 100 
#then the computer guesses the number generated by randomly generating a guess with in the perameters

import random

#program generates a Number to be guessed
print "generating a number"

number = random.randrange(100) +1
low = 1
high = 100

print number

#computer guesses the number
#program asks the player to guess the number and program tracks the number of guesses
guess = random.randrange(low , high) / 2
tries = 1

#program evaluates number
while guess != number:
  if (guess > number):
    high = guess
    print "your guess is too high"
    print "the number is now between ", low, "and", high
    guess = random.randrange(low , high) / 2 + 1
    print guess
    tries += 1
  
  else:
    low = guess
    print "your guess is too low"
    print "the number is now between ",low , "and", high
    guess = random.randrange(low , high) + 1
    print guess
    tries += 1

print "Congratulations, Computer guessed", number, "in", tries, "tries."

raw_input("\nPress enter to exit")