#Documentation MSI List

DOC_LIST = [
		'Altiris_AssetManagementDocumentation_x64.msi',
		'Altiris_BarcodeDocumentation_x64.msi',
		'Altiris_ClientManagementSuiteDocumentation_x64.msi',
		'Altiris_CMDBDocumentation_x64.msi',
		'Altiris_DeploymentSolutionDocumentation_x64.msi',
		'Altiris_ECVDocumentation_x64.msi',
		'Altiris_InventorySolutionDocumentation_x64.msi',
		'Altiris_InventoryNDDocumentation_x64.msi',
		'Altiris_ITAnalyticsDocumentation_x64.msi',
		'Altiris_MonitorDocumentation_x64.msi',
		'Altiris_OOBDocumentation_x64.msi',
		'Altiris_PatchManagementLinuxDocumentation_x64.msi',
		'Altiris_PatchManagementMacDocumentation_x64.msi',
		'Altiris_PatchManagementWindowsDocumentation_x64.msi',
		'Altiris_RTCIDocumentation_x64.msi',
		'Altiris_RTSMDocumentation_x64.msi',
		'Altiris_SEPICDocumentation_x64.msi',
		'Altiris_ServerManagementSuiteDocumentation_x64.msi',
		'Symantec_ServiceDeskDocumentation_x64.msi',
		'Altiris_SoftwareManagementSolutionDocumentation_x64.msi',
		'Altiris_VMMDocumentation_x64.msi',
		'Altiris_WiseConnectorDocumentation_x64.msi',
		'Symantec_pcAnywhereSolutionDocumentation_x64.msi',
		'Altiris_DeploymentDellDocumentation_x64.msi',
		#'Altiris_MobileMgmtDocumentation_7_1_x64.msi',
		'Altiris_DeploymentSolarisDocumentation_x64.msi',
		]
